apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neon-minio.fullname" . }}
  labels:
    {{- include "neon-minio.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Which pods the Deployment is managing (duplicates template.metadata.labels).
  selector:
    matchLabels:
      {{- include "neon-minio.selectorLabels" . | nindent 6 }}
  # Pod template.
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # Labels set on created pods.
      labels:
        {{- include "neon-minio.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "neon-minio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["minio"]
          args: ["server", "/data", "--address", ":{{ .Values.service.port }}", "--console-address", ":{{ .Values.service.httpPort }}"]
          {{- if .Values.settings }}
          env:
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.settings.accessKey.rootPassword }}
            - name: MINIO_ROOT_USER
              value: {{ .Values.settings.accessKey.rootUser }}
          {{- end }}
          ports:
            - name: minio
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: console
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /minio/health/live
              port: minio
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: minio
            periodSeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: minio
            periodSeconds: 15
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
