apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" (include "neon-minio.fullname" .) "create-buckets" | trunc 63 | trimSuffix "-" }}
spec:
  template:
    spec:
      containers:
      - name: minio-mc
        image: minio/mc
        env:
        - name: MINIO_ROOT_USER
          value: {{ .Values.settings.accessKey.rootUser }}
        - name: MINIO_ROOT_PASSWORD
          value: {{ .Values.settings.accessKey.rootPassword }}
        - name: MINIO_URL
          value: {{ printf "http://%s:%d" ( include "neon-minio.fullname" .) (int .Values.service.port) }}
        command:
        - "/bin/sh"
        - "-c"
        - |
          until (/usr/bin/mc alias set minio ${MINIO_URL} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}) do
              echo 'Waiting to start minio...' && sleep 1;
          done;
          /usr/bin/mc mb minio/neon --region=eu-north-1;
      restartPolicy: OnFailure