apiVersion: v1
kind: Service
metadata:
  name: {{ include "neon-minio.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "neon-minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: minio
      protocol: TCP
      name: minio
    - port: {{ .Values.service.httpPort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "neon-minio.selectorLabels" . | nindent 4 }}
