{{- $replicas := int .Values.replicas }}
{{- range $index, $element := until $replicas }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%d" (include "neon-safekeeper.fullname" $) $index }}
  {{- with $.Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "neon-safekeeper.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: service
      protocol: TCP
      name: service
    - port: {{ $.Values.service.httpPort }}
      targetPort: monitor
      protocol: TCP
      name: monitor
  selector:
    {{- include "neon-safekeeper.selectorLabels" $ | nindent 4 }}
    safekeeperId: "{{ $index }}"
{{- end }}